KDAB/knut

- .github/workflows/knut-tests.yml
- CMakeLists.txt
- CMakePresets.json
- src/core/CMakeLists.txt
- src/core/version.cpp.in
- src/core/version.h
- src/gui/mainwindow.cpp
- src/main.cpp
We should be able to speed up our CI by caching the build artifacts using sccache like we do in [https://github.com/KDAB/cxx-qt/](CXX-Qt).
My goal is to stick below 10 min. CI build if at all possible.
Part of #3
> CI: Enable cached builds

- .github/workflows/knut-tests.yml
- .gitmodules
- 3rdparty-kdab/CMakeLists.txt
- 3rdparty/CMakeLists.txt
- CMakeLists.txt
- CMakePresets.json
- README.md
As part of this, let's also move the mfc-utils and photonwidgets submodules into another directory, so that we can check out the public dependencies more easily.
> docs: Update README with build instructions

- CMakeLists.txt
Our current CI partially support C++23, but is limited.
For example std::unexpected is not supported yet.
Revert to using C++20 only for now, until CI is updated.
> chore: move to C++20

- docs/index.md
This is mostly meant to test our Documentation automation, but is also a valid addition
> docs: Add link to our YouTube channel

- .github/workflows/documentation.yml
This is only available if the run is triggered by a Pull Request.
> ci: Remove the reference to base_ref in docs job

- knut.code-workspace
It's not up to me to decide to use the clangd extension.
> chore: Reduce workspace extensions for VSCode

- docs/getting-started/cli.md
- src/core/knutcore.cpp
- src/core/settings.cpp
- src/core/settings.h
The settings are returned as a json file, that could then be used by 3rdparty.
Original Author: Matt Aber (sorry, I messed up with git)
Fix #35
> feat: add option to return the settings from the CLI

- CMakeLists.txt
MFC scripts have been updated following the new API, all tests are green now.
> fix(tests): update mfc-utils for tests to pass

- src/core/qttsdocument.cpp
- test_data/tst_qttsdocument/language_translation.ts
- tests/tst_qttsdocument.cpp
> fix: modification of the setTranslation function for the case where the node is untranslated

- .github/workflows/knut-tests.yml
This is now done by pre-commit.ci, which is faster and should even be
able to auto-fix certain things.
> chore(ci): Remove pre_commit job from GH Actions

- CMakeLists.txt
Add a KNUT_UPDATE_DOCS option in CMake to optionally disable the
automatic documentation generation.
This is necessary as Qt Creator apparently fails running cpp2doc.
Fix #59
> chore(cmake): Re-enable docs target by default

- src/core/settings.cpp
- tests/tst_settings.cpp
before this commit, we didn't save json files in test mode, so as not to overwrite the json file already present in the user's home directory. now we save this json file in the temp directory.
We have also improved tst_settings.cpp, which now saves the json file in the temp directory.
> fix: save settings file in different directory in testing mode

- docs/API/knut/settings.md
- src/core/settings.cpp
- src/core/settings.h
- test_data/tst_settings.qml
- test_data/tst_settings/setValue/knut.json.expected
- test_data/tst_settings_rw.qml
- tests/tst_knut.cpp
- tests/tst_settings.cpp
We can't use a QVariant, as it does not support list.
We have to take a QJSValue, and transform it in a QVariant ?!
> fix: Fix saving stringlist in Settings via script

- docs/API/knut/codedocument.md
- src/core/codedocument.cpp
- src/core/codedocument.h
- src/core/codedocument_p.cpp
- src/core/codedocument_p.h
- src/gui/mainwindow.cpp
- src/gui/mainwindow.h
- src/gui/mainwindow.ui
- src/treesitter/CMakeLists.txt
- src/treesitter/node.cpp
- src/treesitter/node.h
- src/treesitter/tree_cursor.cpp
- src/treesitter/tree_cursor.h
- tests/tst_codedocument.cpp
This allows navigating the code semantically.
Fix #64
> feat: Select Smaller/Larger/Next/Previous Syntax Nodes

- docs/API/knut/cppdocument.md
- src/core/codedocument.cpp
- src/core/codedocument.h
- src/core/codedocument_p.cpp
- src/core/core/settings.json
- src/core/cppdocument.cpp
- src/core/cppdocument.h
- src/core/settings.h
- src/gui/optionsdialog.cpp
- src/gui/optionsdialog.h
- src/gui/optionsdialog.ui
- src/gui/treesitterinspector.cpp
- src/gui/treesittertreemodel.cpp
- src/treesitter/parser.cpp
- src/treesitter/parser.h
- test_data/tst_cppdocument/treesitterExcludesMacros/AFX_EXT_CLASS.h
- tests/tst_cppdocument_treesitter.cpp
We can use TreeSitters "included ranges" to specify which parts of the document to include when parsing.
In our case we actually use this to exclude certain ranges, which are C++ pre-processor macros that would otherwise screw up our parsing.
Fix #30
> feat: Skip macros in C++ during parsing

- src/core/knutcore.cpp
- src/core/settings.cpp
- src/core/settings.h
We add a way to save settings before exiting if there are changes. This make the tests to pass with the corrected knut.json
> fix: save settings on exit

- src/core/scriptdialogitem.cpp
- src/core/scriptdialogitem.h
- if the string is empty (ie calling nextStep()), then repeat the previous string
- Depends on : https://codereview.kdab.com/c/kdab/mfc-utils/+/144576
> feat: improve nextStep API in ScriptDialog

- docs/API/knut/typedsymbol.md
- mkdocs.yml
- src/core/CMakeLists.txt
- src/core/cppdocument.cpp
- src/core/functionsymbol.cpp
- src/core/symbol.cpp
- src/core/typedsymbol.cpp
- src/core/typedsymbol.h
- test_data/tst_symbol/return_type.h
- test_data/tst_symbol/typedsymbol.h
- tests/tst_symbol.cpp
Make sure that the type information returned by symbols is accurate by:
1. Adding a TypedSymbol that knows about the type of its symbol
2. Making sure FunctionSymbol can extract complex type signatures correctly
Fix #117
> Check type information provided by symbols

- src/gui/treesitterinspector.cpp
- src/gui/treesitterinspector.h
This uses KSyntaxHighlighting::SyntaxHighlighter to enable a
scheme-based syntax highlighting on the TreeSitterInspector.
This still has a few issues, as e.g. #eq? produces a strange
highlighting result and certain keywords are marked up without reason.
But it's still a good improvement from no syntax highlighting.
Part of #62.
> feat: Scheme syntax highlighting for TreeSitter

- src/core/knutcore.cpp
- src/core/scriptdialogitem.cpp
- src/core/scriptdialogitem.h
- src/core/scriptmanager.cpp
- src/core/scriptmanager.h
- src/core/scriptrunner.cpp
- src/core/scriptrunner.h
- src/core/utils.cpp
Fixes KDAB#32
Tested in de MR : https://codereview.kdab.com/c/kdab/mfc-utils/+/144788
> feat: add a way to initialize script dialog from command line

- src/lsp/types.h
warning concerned:
726:40: warning: '/*' within block comment [-Wcomment]
- `{}` to group conditions (e.g. `**<U+200B>/*.{ts,js}` matches all TypeScript and JavaScript files)
> fix: change syntax of comments to remove warning

- examples/ex_script_dialog.qml
- examples/ex_script_dialog.ui
- src/core/CMakeLists.txt
- src/core/scriptdialogitem.cpp
- src/core/scriptdialogitem.h
Fixes KDAB#27
to use the syntax highlighting of the "data.foo" widget, just use the name of the extension like "cpp", "js" or "py" in the "data.fooSyntax" property
> feat: Handle QTextEdit in the ScriptDialogItem

- src/core/knutcore.cpp
The existing code was only enabling flush when logs are redirected to files.
Without this, the relative order of the debug output from qWarnings() and from Message.log() wasn't preserved, making debugging difficult.
> fix: flush spdlog messages also when logging to stderr

- docs/API/knut/classsymbol.md
- docs/API/knut/dataexchange.md
- docs/API/knut/functionsymbol.md
- docs/API/knut/messagemap.md
- docs/API/knut/messagemapentry.md
- docs/API/knut/querymatch.md
- tools/cpp2doc/docwriter.cpp
- tools/cpp2doc/sourceparser.cpp
makes documentation generation easier by allowing writing types with nested angle brackets like `array<map<string, int>>`
> fix: allows describing type documentation with nested brackets and commas

- src/gui/gui.qrc
- src/gui/gui/treesitter-query.xml
- src/gui/treesitterinspector.cpp
Add a modified version of the scheme grammar for even better query
syntax highlighting.
This should now correctly highlights captures and predicates.
Related to #62 
Example with my current theme:
> feat: Custom treesitter grammar

- docs/API/knut/project.md
- src/core/project.cpp
- src/core/project.h
- test_data/tst_project.qml
The methode return a list of document + position of the find items.
The method uses ripgrep (rg) for searching, which must be installed and accessible in PATH.
The `pattern` parameter should be a valid regular expression.
Fixes KDAB#21
> feat: add a find in files API to `Project`

- docs/API/knut/cppdocument.md
- src/core/cppdocument.cpp
- src/core/cppdocument.h
- test_data/tst_cppdocument/removeLines/myobject.h.expected
- test_data/tst_cppdocument/removeLines/myobject.h.original
- tests/tst_cppdocument.cpp
> feat: add a removeLines method in CppDocument

- docs/API/knut/scriptdialog.md
- examples/ex_gui_interactive.qml
- src/core/scriptdialogitem.cpp
- src/core/scriptdialogitem.h
- src/core/scriptprogressdialog.cpp
- src/core/scriptprogressdialog.h
- src/core/scriptprogressdialog.ui
Added a QPlainTextEdit widget to allow real-time log display in the user interface. The actual code did not allow windows users to view logs when launching knut from the command line.
The QPlainTextEdit can be made visible using the qml setDisplayLogs method and taking as parameter the minimum log level that we want to have.
Fixes https://github.com/KDAB/knut/issues/26
> feat: add a way to display log in a ScriptDialog

- src/core/scriptdialogitem.cpp
move the returns to be sure that if a condition is not verified then we reach the case where the widget is not supported
> fix: move return in the changeValue method to ensure proper execution flow

- tools/cpp2doc/docwriter.cpp
improves execution speed by 16% in Debug mode :
- before : 0.054s
- after : 0.045s
Fixes: KDAB#101
> fix: use asKeyValueRange() instead of keys()

- CMakeLists.txt
Qt 6.5 is the current LTS.
Closes #4
> build: bump Qt minimum version to Qt 6.5

- src/core/scriptdialogitem_p.cpp
- src/core/scriptdialogitem_p.h
It was null until ready() was called, but before that, any qobject_cast on the object would crash.
In Qt 6.8 QAccessibleWidget looks for "who has widget X as buddy" by iterating over all children() of the parent and doing qobject_cast<QLabel *>, hence this new crash.
> fix: fix crash with Qt 6.8: metaObject() should never be nullptr

- src/gui/CMakeLists.txt
- src/gui/findinterface.h
- src/gui/findwidget.cpp
- src/gui/findwidget.h
- src/gui/findwidget.ui
- src/gui/highlightdelegate.cpp
- src/gui/highlightdelegate.h
- src/gui/mainwindow.cpp
- src/gui/mainwindow.h
- src/gui/qttsview.cpp
- src/gui/qttsview.h
- src/gui/qtuiview.cpp
- src/gui/qtuiview.h
- src/gui/searchabletableview.cpp
- src/gui/searchabletableview.h
- src/gui/textview.cpp
- src/gui/textview.h
- add a new interface for searching into document view
- move the textdocument search to this new interface
- implement the interface for QtUiDocument and QtTsDocument
Related to #25
> feat: improve search in document

- src/gui/findwidget.cpp
- src/gui/findwidget.ui
The find widget height is always minimum, even when the replace line is
hidden.
> fix: Ensure the find widget's height is minimum

- src/gui/palette.cpp
- src/gui/palette.h
The palette is just a way to navigate around, it shouldn't be able to
create new files.
Also keep the palette open if the text does not match (like VS Code).
> fix: Do not create new files from the palette

- src/gui/apiexecutorwidget.ui
When changing files with the API executor displayed, the combobox didn't
adapt to its content.
Fix #164
> fix: Fix combobox's width for API executor

- src/core/jsondocument.cpp
The loading was working to be able to use the JsonDocument API, but it
didn't work in the GUI to display the file.
This is fixed, and we update the underlying json model after each save.
> fix: Fix json loading in gui

- docs/API/knut/rcdocument.md
- docs/API/knut/textdocument.md
- src/core/logger.cpp
- src/core/logger.h
- src/core/rcdocument.cpp
- src/core/rcdocument.h
- src/core/textdocument.cpp
- src/core/textdocument.h
- src/gui/textview.cpp
This makes it easier for a human to read and edit the script after the fact.
Mostly useful for the find API in TextDocument
Fix #177
> feat: Use enum values rather than int for recording

- src/core/lsp_utils.cpp
Otherwise, there's a createRangeMark method logged when showing lsp
documentation for the symbol.
> fix: Don't log anything on hover

- src/gui/scriptpanel.cpp
- src/gui/scriptpanel.h
This will avoid losing the changes made to the script when the user
tries to create or open a new script without saving the current one.
> fix: Ask user to save modified script before new one

- .github/workflows/submodule-bump.yml
Allows to print the overall current versions and latest versions of all submodules.
Also allows to update submodules to their latest version.
The maintainer needs to manually trigger this workflow, it won't be scheduled.
> ci: add submodule-bump.yml

- .gitmodules
- 3rdparty/CMakeLists.txt
- README.md
- docs/index.md
- src/core/CMakeLists.txt
- src/core/codedocument.cpp
- src/core/core/settings.json
- src/core/csharpdocument.cpp
- src/core/csharpdocument.h
- src/core/document.h
- src/core/project.cpp
- src/gui/apiexecutorwidget.cpp
- src/gui/mainwindow.cpp
- src/treesitter/CMakeLists.txt
- src/treesitter/languages.h
- src/treesitter/parser.cpp
Currently, this only includes basic support for the TreeSitter grammar,
without support for symbols or LSP.
> feat: Add basic support for C# documents

- src/gui/codeview.cpp
- src/gui/mainwindow.cpp
- src/gui/qmlview.cpp
- src/gui/qmlview.h
- src/gui/qttsview.cpp
- src/gui/qttsview.h
- src/gui/qtuiview.cpp
- src/gui/qtuiview.h
- src/gui/scriptpanel.cpp
Fix memory leaks regarding:
- Code file viewer
- UI file viewer
- Slint file viewer
- Image file viewer
- TS translation file viewer
- Script panel
> Fix memory leaks

- .gitmodules
- 3rdparty/CMakeLists.txt
- README.md
- docs/API/knut/codedocument.md
- docs/index.md
- src/core/CMakeLists.txt
- src/core/codedocument.cpp
- src/core/core/settings.json
- src/core/document.h
- src/core/project.cpp
- src/core/rustdocument.cpp
- src/core/rustdocument.h
- src/gui/apiexecutorwidget.cpp
- src/gui/mainwindow.cpp
- src/treesitter/CMakeLists.txt
- src/treesitter/languages.h
- src/treesitter/parser.cpp
Currently, this only includes basic support for the TreeSitter grammar,
without support for symbols or LSP.
> feat: Add basic support for Rust documents

- src/gui/CMakeLists.txt
- src/gui/knuttabwidget.cpp
- src/gui/knuttabwidget.h
- src/gui/mainwindow.cpp
- src/gui/mainwindow.h
- src/gui/mainwindow.ui
Allow closing documents by clicking X in their tabs.
> Make document tabs closable

- src/core/project.cpp
- src/core/settings.cpp
- src/core/settings.h
- src/gui/mainwindow.cpp
- src/gui/mainwindow.h
Opening a new project closes all files and replaces the current project.
> Allow opening a different project

- src/core/qttsdocument.cpp
Unicode support is required for source and comment fields because:
- Qt supports those characters in Qt Linguist files
- Languages other than English can be used for source and to comment
- Punctuation outside of the scope of Latin1 can be present in English
E.g. Ellipsis …
> fix: Add missing Unicode support to translation messages

- src/gui/scriptpanel.cpp
This change is meant to boost productivity when prototyping a Knut script from the ScriptPanel.
Behavior aims to replicate what one finds in Qt Creator and standard editors. Pressing Enter|Return results in a line that has been properly indented relative to the current line. When a new block is about to begin, a new indentation is added. Blocks are determined by checking for Javascript verbs that result in a block and by checking for an opening curly brace.
When an opening brace is typed, the closing brace that follows is inserted automatically. Typing a closing brace after a closing brace was automatically inserted results in the cursor being moved to the right of the automatically typed brace. Pressing Enter after a right brace was automatically inserted results in the closing brace …
> feat: Auto indent when Enter is pressed in ScriptPanel

- src/core/qttsdocument.cpp
Writing a node_pcdata when a the numerusform node_element is already present results in a .ts file that can't be opened by QLinguist. This is a fix to prevent .ts files with plurals from getting broken by Knut. Proper support for plurals still needs to be added.
> fix: Prevent Knut from breaking file when writing plural translations

- src/core/document.cpp
- src/core/document.h
- src/gui/mainwindow.cpp
When a file is changed both internally and externally, a dialog shows
up on focus to ask to reload and lose the changes. If the answer was
no, the same dialog would have appeared again on the next focus.
It's now fixed, the dialog shows up only once.
Fix #252
> fix: file changed externally triggers the message all the time
